import { Images } from '../constants/Images';

export const mockEvents = [
  {
    id: '1',
    title: 'Digital Transformation Summit 2025',
    description: 'Leading conference on digital innovation across industries',
    date: '2025-02-15',
    imageUrl: Images.event1,
    joinLink: 'support@techforward.net',
    location: 'San Francisco, CA',
    industry: 'Technology',
    company: 'TechForward Inc.',
    attendees: 450,
    type: 'conference'
  },
  {
    id: '2',
    title: 'Sustainable Manufacturing Workshop',
    description: 'Hands-on workshop for sustainable practices in manufacturing',
    date: '2025-02-20',
    imageUrl: Images.event2,
    joinLink: 'contact@greenmanufacturing.org',
    location: 'Detroit, MI',
    industry: 'Manufacturing',
    company: 'Green Manufacturing Co.',
    attendees: 85,
    maxAttendees: 100,
    type: 'workshop'
  },
  {
    id: '3',
    title: 'Healthcare Innovation Network',
    description: 'Networking event for healthcare professionals and innovators',
    date: '2025-02-25',
    imageUrl: Images.event3,
    location: 'Boston, MA',
    industry: 'Healthcare',
    company: 'MedInnovate',
    attendees: 200,
    maxAttendees: 250,
    type: 'networking'
  },
  {
    id: '4',
    title: 'Financial Services Seminar',
    description: 'Latest trends and regulations in financial services',
    date: '2025-03-01',
    imageUrl: Images.event4,
    joinLink: 'support@financefirst.net',
    location: 'New York, NY',
    industry: 'Finance',
    company: 'FinanceFirst',
    attendees: 150,
    maxAttendees: 200,
    type: 'seminar'
  },
  {
    id: '5',
    title: 'Renewable Energy Conference',
    description: 'Exploring the future of sustainable energy solutions',
    date: '2025-03-05',
    imageUrl: Images.event5,
    location: 'Austin, TX',
    industry: 'Energy',
    company: 'GreenTech Solutions',
    attendees: 320,
    maxAttendees: 400,
    type: 'conference'
  },
  {
    id: '6',
    title: 'Agricultural Innovation Workshop',
    description: 'Modern farming techniques and sustainable agriculture',
    date: '2025-03-10',
    imageUrl: Images.event5,
    location: 'Des Moines, IA',
    industry: 'Agriculture',
    company: 'AgriTech Corp',
    attendees: 75,
    maxAttendees: 120,
    type: 'workshop'
  }
];

export const mockVacancies = [
  {
    id: '1',
    industry: 'Technology',
    type: 'full-time',
    description: 'Join our team to optimize manufacturing processes and implement lean manufacturing principles.',
    imageUrl: Images.vacancy1,
    postedDate: '2025-01-15',
    recruitmentEmail: 'mdzeshh@gmail.com'
  },
  {
    id: '2',
    industry: 'Manufacturing',
    type: 'full-time',
    description: 'We are looking for a senior software engineer to join our growing team and lead development of our core platform.',
    imageUrl: Images.vacancy2,
    postedDate: '2025-01-18',
  },
  {
    id: '3',
    industry: 'Healthcare',
    type: 'full-time',
    imageUrl: Images.vacancy3,
    postedDate: '2025-01-20',
    recruitmentEmail: 'mdzeshh@gmail.com'
  },
  {
    id: '4',
    industry: 'Marketing',
    type: 'full-time',
    imageUrl: Images.vacancy4,
    postedDate: '2025-01-22'
  },
  {
    id: '5',
    industry: 'Education',
    type: 'full-time',
    imageUrl: Images.vacancy5,
    postedDate: '2025-01-25',
    recruitmentEmail: 'mdzeshh@gmail.com'
  },
  {
    id: '6',
    industry: 'Manufacturing',
    type: 'part-time',
    description: 'Coordinate clinical trials and ensure compliance with regulatory requirements.',
    imageUrl: Images.vacancy6,
    postedDate: '2025-01-25'
  },
  {
    id: '7',
    industry: 'Oil & Gas',
    type: 'part-time',
    description: 'Lead marketing campaigns and brand strategy for diverse client portfolio.',
    imageUrl: Images.vacancy7,
    postedDate: '2025-01-25',
    recruitmentEmail: 'mdzeshh@gmail.com'
  },
  {
    id: '8',
    industry: 'Education',
    type: 'full-time',
    imageUrl: Images.vacancy8,
    postedDate: '2025-01-25'
  },
  {
    id: '9',
    industry: 'Finance',
    type: 'full-time',
    imageUrl: Images.vacancy9,
    postedDate: '2025-01-25',
    recruitmentEmail: 'mdzeshh@gmail.com'
  },
  {
    id: '10',
    industry: 'Marketing',
    type: 'full-time',
    description: 'Passionate educator needed for 3rd grade classroom with focus on STEM integration.',
    imageUrl: Images.vacancy10,
    postedDate: '2025-01-25',
    recruitmentEmail: 'mdzeshh@gmail.com'
  },
  {
    id: '11',
    industry: 'Energy',
    type: 'part-time',
    imageUrl: Images.vacancy11,
    postedDate: '2025-01-25'
  }
];

export const mockTenders = [
  {
    id: '1',
    title: 'Road Construction Project - Manzini Region',
    imageUrl: Images.tender1,
    posterUrl: Images.tender1, // Some have posters
    hasPoster: true,
    hasDetails: true,
    industry: 'Construction',
    category: 'Construction',
    organization: 'Ministry of Public Works',
    description: 'Construction and rehabilitation of 15km rural road network in Manzini region. The project includes road widening, drainage systems, and asphalt overlay.',
    detailedDescription: 'This comprehensive road construction project aims to improve connectivity and economic opportunities in the Manzini region. The scope includes:\n\n• Road widening to 7 meters\n• Installation of proper drainage systems\n• Asphalt overlay for existing roads\n• Construction of culverts and bridges\n• Road marking and signage\n• Environmental impact mitigation measures',
    budget: 'E 2,500,000',
    budgetRange: { min: 2300000, max: 2700000 },
    deadline: '2025-11-15',
    deadlineTime: '17:00',
    postedDate: '2025-01-10',
    daysLeft: 12,
    status: 'Open',
    urgent: true,
    location: 'Manzini Region',
    enquiryEmail: 'tenders@publicworks.gov.sz',
    enquiryPhone: '+268 2404 1234',
    requirements: [
      'Valid contractor license',
      'Minimum 5 years experience in road construction',
      'Equipment list with ownership certificates',
      'Financial statements (last 3 years)',
      'Tax clearance certificate',
      'Insurance certificate',
      'Company registration documents',
      'Technical proposal',
      'Environmental compliance certificate'
    ],
    bidRequirements: {
      companyName: true,
      companyRegistration: true,
      taxClearance: true,
      financialStatements: true,
      technicalProposal: true,
      financialProposal: true,
      insuranceCertificate: true,
      experienceCertificate: true,
      equipmentList: true,
      references: true,
      bankGuarantee: false
    },
    numberOfBids: 8,
    isPublished: true,
  },
  {
    id: '2',
    title: 'IT Infrastructure Upgrade',
    imageUrl: Images.tender2,
    posterUrl: null, // No poster, details only
    hasPoster: false,
    hasDetails: true,
    industry: 'IT Services',
    category: 'IT Services',
    organization: 'Eswatini Revenue Authority',
    description: 'Supply and installation of network infrastructure and server equipment for enterprise-level operations.',
    detailedDescription: 'The Eswatini Revenue Authority requires a complete IT infrastructure overhaul to support digital transformation initiatives. The project includes:\n\n• Network infrastructure design and installation\n• Server room setup with cooling systems\n• Data center equipment procurement\n• Network security implementation\n• Backup and disaster recovery systems\n• Staff training and documentation',
    budget: 'E 850,000',
    budgetRange: { min: 800000, max: 900000 },
    deadline: '2025-11-30',
    deadlineTime: '16:00',
    postedDate: '2025-01-05',
    daysLeft: 27,
    status: 'Open',
    urgent: false,
    location: 'Mbabane',
    enquiryEmail: 'procurement@era.gov.sz',
    enquiryPhone: '+268 2404 5678',
    requirements: [
      'ISO certification',
      'Technical proposal',
      'Financial statements',
      'Vendor certifications',
      'Support and maintenance plan'
    ],
    bidRequirements: {
      companyName: true,
      companyRegistration: true,
      taxClearance: true,
      financialStatements: true,
      technicalProposal: true,
      financialProposal: true,
      insuranceCertificate: true,
      experienceCertificate: true,
      certifications: true,
      references: true,
      bankGuarantee: false
    },
    numberOfBids: 5,
    isPublished: true,
  },
  {
    id: '3',
    title: 'Medical Supplies Procurement',
    imageUrl: Images.tender3,
    posterUrl: Images.tender3, // Has poster
    hasPoster: true,
    hasDetails: true,
    industry: 'Healthcare',
    category: 'Supplies',
    organization: 'Ministry of Health',
    description: 'Supply of essential medical equipment and pharmaceutical supplies for public health facilities.',
    detailedDescription: 'The Ministry of Health is procuring essential medical supplies for distribution across public health facilities in Eswatini. This includes:\n\n• Pharmaceuticals and medicines\n• Medical equipment and devices\n• Laboratory supplies\n• Personal protective equipment (PPE)\n• Hospital consumables\n• Emergency medical kits',
    budget: 'E 1,200,000',
    budgetRange: { min: 1100000, max: 1300000 },
    deadline: '2025-11-08',
    deadlineTime: '15:00',
    postedDate: '2025-01-12',
    daysLeft: 5,
    status: 'Open',
    urgent: true,
    location: 'Nationwide',
    enquiryEmail: 'procurement@health.gov.sz',
    enquiryPhone: '+268 2404 9012',
    requirements: [
      'Valid pharmacy license',
      'Quality certificates',
      'Delivery timeline',
      'Storage facility certification',
      'Good Distribution Practice (GDP) certificate'
    ],
    bidRequirements: {
      companyName: true,
      companyRegistration: true,
      taxClearance: true,
      financialStatements: true,
      technicalProposal: true,
      financialProposal: true,
      insuranceCertificate: true,
      licenseCertificate: true,
      qualityCertificates: true,
      references: true,
      bankGuarantee: true
    },
    numberOfBids: 12,
    isPublished: true,
  },
  {
    id: '4',
    title: 'Solar Panel Installation Project',
    imageUrl: Images.tender4,
    posterUrl: Images.tender4,
    hasPoster: true,
    hasDetails: false, // Poster only
    industry: 'Energy',
    category: 'Energy',
    organization: 'Eswatini Water Services',
    description: 'Solar panel installation and grid integration for municipal buildings.',
    detailedDescription: 'Installation of solar panels on municipal buildings to reduce electricity costs and promote renewable energy.',
    budget: 'E 1,500,000',
    budgetRange: { min: 1400000, max: 1600000 },
    deadline: '2025-12-01',
    deadlineTime: '17:00',
    postedDate: '2025-01-08',
    daysLeft: 28,
    status: 'Open',
    urgent: false,
    location: 'Mbabane, Manzini',
    enquiryEmail: 'tenders@water.gov.sz',
    enquiryPhone: '+268 2404 3456',
    requirements: [
      'Solar installation certification',
      'Electrical contractor license',
      'Project portfolio',
      'Warranty terms'
    ],
    bidRequirements: {
      companyName: true,
      companyRegistration: true,
      taxClearance: true,
      financialStatements: true,
      technicalProposal: true,
      financialProposal: true,
      insuranceCertificate: true,
      experienceCertificate: true,
      certifications: true,
      references: true,
      bankGuarantee: false
    },
    numberOfBids: 6,
    isPublished: true,
  },
  {
    id: '5',
    title: 'Agricultural Equipment Supply',
    imageUrl: Images.tender5,
    posterUrl: null,
    hasPoster: false,
    hasDetails: true,
    industry: 'Agriculture',
    category: 'Supplies',
    organization: 'Ministry of Agriculture',
    description: 'Supply of modern farming equipment and machinery for agricultural development programs.',
    detailedDescription: 'Procurement of agricultural equipment to support small-scale and commercial farmers across Eswatini.',
    budget: 'E 980,000',
    budgetRange: { min: 900000, max: 1050000 },
    deadline: '2025-11-20',
    deadlineTime: '16:00',
    postedDate: '2025-01-08',
    daysLeft: 17,
    status: 'Open',
    urgent: false,
    location: 'Nationwide',
    enquiryEmail: 'procurement@agriculture.gov.sz',
    enquiryPhone: '+268 2404 7890',
    requirements: [
      'Equipment specifications',
      'Delivery schedule',
      'Warranty information',
      'After-sales service plan'
    ],
    bidRequirements: {
      companyName: true,
      companyRegistration: true,
      taxClearance: true,
      financialStatements: true,
      technicalProposal: true,
      financialProposal: true,
      insuranceCertificate: true,
      experienceCertificate: true,
      equipmentCatalog: true,
      references: true,
      bankGuarantee: false
    },
    numberOfBids: 4,
    isPublished: true,
  },
  {
    id: '6',
    title: 'Financial Audit Services',
    imageUrl: Images.tender6,
    posterUrl: null,
    hasPoster: false,
    hasDetails: true,
    industry: 'Consulting',
    category: 'Consulting',
    organization: 'Eswatini Water Services',
    description: 'External audit services for fiscal year 2024/2025.',
    detailedDescription: 'Comprehensive financial audit services for the fiscal year 2024/2025, including compliance review and recommendations.',
    budget: 'E 450,000',
    budgetRange: { min: 400000, max: 500000 },
    deadline: '2025-12-15',
    deadlineTime: '17:00',
    postedDate: '2025-01-08',
    daysLeft: 42,
    status: 'Open',
    urgent: false,
    location: 'Mbabane',
    enquiryEmail: 'finance@water.gov.sz',
    enquiryPhone: '+268 2404 2468',
    requirements: [
      'Registered audit firm',
      'Relevant experience',
      'Team qualifications',
      'Audit methodology',
      'Timeline proposal'
    ],
    bidRequirements: {
      companyName: true,
      companyRegistration: true,
      taxClearance: true,
      financialStatements: true,
      technicalProposal: true,
      financialProposal: true,
      insuranceCertificate: true,
      auditLicense: true,
      teamCVs: true,
      references: true,
      bankGuarantee: false
    },
    numberOfBids: 3,
    isPublished: true,
  },
  {
    id: '7',
    title: 'Building Construction - New Office Complex',
    imageUrl: Images.tender7,
    posterUrl: Images.tender7,
    hasPoster: true,
    hasDetails: true,
    industry: 'Construction',
    category: 'Construction',
    organization: 'Ministry of Public Works',
    description: 'Construction of a new 5-story office complex in Mbabane city center.',
    detailedDescription: 'Design and construction of a modern office complex to house government departments.',
    budget: 'E 8,500,000',
    budgetRange: { min: 8000000, max: 9000000 },
    deadline: '2025-12-10',
    deadlineTime: '17:00',
    postedDate: '2025-01-08',
    daysLeft: 37,
    status: 'Open',
    urgent: false,
    location: 'Mbabane',
    enquiryEmail: 'tenders@publicworks.gov.sz',
    enquiryPhone: '+268 2404 1234',
    requirements: [
      'Building contractor license',
      'Architectural plans',
      'Structural engineering certification',
      'Project timeline',
      'Safety compliance certificate'
    ],
    bidRequirements: {
      companyName: true,
      companyRegistration: true,
      taxClearance: true,
      financialStatements: true,
      technicalProposal: true,
      financialProposal: true,
      insuranceCertificate: true,
      experienceCertificate: true,
      buildingLicense: true,
      references: true,
      bankGuarantee: true
    },
    numberOfBids: 7,
    isPublished: true,
  },
  {
    id: '8',
    title: 'Fleet Vehicle Procurement',
    imageUrl: Images.tender8,
    posterUrl: null,
    hasPoster: false,
    hasDetails: true,
    industry: 'Transportation',
    category: 'Supplies',
    organization: 'Ministry of Transport',
    description: 'Procurement of 20 passenger vehicles for government fleet.',
    detailedDescription: 'Purchase of reliable passenger vehicles to enhance government transportation services.',
    budget: 'E 2,200,000',
    budgetRange: { min: 2000000, max: 2400000 },
    deadline: '2025-11-25',
    deadlineTime: '16:00',
    postedDate: '2025-01-08',
    daysLeft: 22,
    status: 'Open',
    urgent: false,
    location: 'Mbabane',
    enquiryEmail: 'procurement@transport.gov.sz',
    enquiryPhone: '+268 2404 1357',
    requirements: [
      'Vehicle specifications',
      'Delivery timeline',
      'Warranty terms',
      'After-sales service',
      'Maintenance package'
    ],
    bidRequirements: {
      companyName: true,
      companyRegistration: true,
      taxClearance: true,
      financialStatements: true,
      technicalProposal: true,
      financialProposal: true,
      insuranceCertificate: true,
      dealershipLicense: true,
      vehicleCatalog: true,
      references: true,
      bankGuarantee: false
    },
    numberOfBids: 9,
    isPublished: true,
  },
  {
    id: '9',
    title: 'Telecommunications Network Expansion',
    imageUrl: Images.tender9,
    posterUrl: Images.tender9,
    hasPoster: true,
    hasDetails: true,
    industry: 'Telecommunications',
    category: 'IT Services',
    organization: 'Eswatini Posts and Telecommunications',
    description: 'Expansion of telecommunications network infrastructure to rural areas.',
    detailedDescription: 'Installation of telecommunications towers and infrastructure to improve connectivity in rural regions.',
    budget: 'E 3,800,000',
    budgetRange: { min: 3500000, max: 4100000 },
    deadline: '2025-12-05',
    deadlineTime: '17:00',
    postedDate: '2025-01-08',
    daysLeft: 32,
    status: 'Open',
    urgent: false,
    location: 'Rural Areas',
    enquiryEmail: 'tenders@eptc.gov.sz',
    enquiryPhone: '+268 2404 9753',
    requirements: [
      'Telecom infrastructure experience',
      'Technical certifications',
      'Project management team',
      'Quality assurance plan'
    ],
    bidRequirements: {
      companyName: true,
      companyRegistration: true,
      taxClearance: true,
      financialStatements: true,
      technicalProposal: true,
      financialProposal: true,
      insuranceCertificate: true,
      experienceCertificate: true,
      certifications: true,
      references: true,
      bankGuarantee: true
    },
    numberOfBids: 6,
    isPublished: true,
  },
  {
    id: '10',
    title: 'Educational Supplies Procurement',
    imageUrl: Images.tender10,
    posterUrl: null,
    hasPoster: false,
    hasDetails: true,
    industry: 'Education',
    category: 'Supplies',
    organization: 'Ministry of Education',
    description: 'Supply of educational materials and equipment for public schools.',
    detailedDescription: 'Procurement of textbooks, laboratory equipment, and educational technology for schools nationwide.',
    budget: 'E 1,800,000',
    budgetRange: { min: 1650000, max: 1950000 },
    deadline: '2025-11-18',
    deadlineTime: '15:00',
    postedDate: '2025-01-08',
    daysLeft: 15,
    status: 'Open',
    urgent: false,
    location: 'Nationwide',
    enquiryEmail: 'procurement@education.gov.sz',
    enquiryPhone: '+268 2404 8642',
    requirements: [
      'Product catalog',
      'Quality certifications',
      'Delivery plan',
      'Training support'
    ],
    bidRequirements: {
      companyName: true,
      companyRegistration: true,
      taxClearance: true,
      financialStatements: true,
      technicalProposal: true,
      financialProposal: true,
      insuranceCertificate: true,
      experienceCertificate: true,
      productCatalog: true,
      references: true,
      bankGuarantee: false
    },
    numberOfBids: 11,
    isPublished: true,
  },
  {
    id: '11',
    title: 'Water Infrastructure Rehabilitation',
    imageUrl: Images.tender11,
    posterUrl: Images.tender11,
    hasPoster: true,
    hasDetails: true,
    industry: 'Government',
    category: 'Construction',
    organization: 'Eswatini Water Services',
    description: 'Rehabilitation and upgrade of water supply infrastructure in urban areas.',
    detailedDescription: 'Comprehensive rehabilitation of aging water infrastructure to improve supply reliability and quality.',
    budget: 'E 5,200,000',
    budgetRange: { min: 4800000, max: 5600000 },
    deadline: '2025-12-20',
    deadlineTime: '17:00',
    postedDate: '2025-01-08',
    daysLeft: 47,
    status: 'Open',
    urgent: false,
    location: 'Urban Areas',
    enquiryEmail: 'tenders@water.gov.sz',
    enquiryPhone: '+268 2404 3456',
    requirements: [
      'Water engineering experience',
      'Project portfolio',
      'Equipment specifications',
      'Environmental compliance'
    ],
    bidRequirements: {
      companyName: true,
      companyRegistration: true,
      taxClearance: true,
      financialStatements: true,
      technicalProposal: true,
      financialProposal: true,
      insuranceCertificate: true,
      experienceCertificate: true,
      engineeringLicense: true,
      references: true,
      bankGuarantee: true
    },
    numberOfBids: 5,
    isPublished: true,
  },
  {
    id: '12',
    title: 'Uniform Supply for Public Servants',
    imageUrl: Images.tender12,
    posterUrl: Images.tender12,
    hasPoster: true,
    hasDetails: false, // Poster only
    industry: 'Fashion',
    category: 'Supplies',
    organization: 'Ministry of Public Service',
    description: 'Supply of uniforms for public servants across various departments.',
    detailedDescription: 'Procurement of high-quality uniforms meeting government specifications.',
    budget: 'E 650,000',
    budgetRange: { min: 600000, max: 700000 },
    deadline: '2025-11-12',
    deadlineTime: '16:00',
    postedDate: '2025-01-08',
    daysLeft: 9,
    status: 'Open',
    urgent: true,
    location: 'Nationwide',
    enquiryEmail: 'procurement@publicservice.gov.sz',
    enquiryPhone: '+268 2404 7531',
    requirements: [
      'Sample products',
      'Quality standards compliance',
      'Production capacity',
      'Delivery schedule'
    ],
    bidRequirements: {
      companyName: true,
      companyRegistration: true,
      taxClearance: true,
      financialStatements: true,
      technicalProposal: true,
      financialProposal: true,
      insuranceCertificate: true,
      experienceCertificate: true,
      productSamples: true,
      references: true,
      bankGuarantee: false
    },
    numberOfBids: 15,
    isPublished: true,
  }
];

// Mock data for user bids
export const mockUserBids = [
  {
    id: 'bid1',
    tenderId: '1',
    tenderTitle: 'Road Construction Project - Manzini Region',
    organization: 'Ministry of Public Works',
    bidAmount: 'E 2,450,000',
    status: 'Submitted',
    submittedDate: '2025-01-20',
    deadline: '2025-11-15',
    category: 'Construction',
    imageUrl: Images.tender1,
  },
  {
    id: 'bid2',
    tenderId: '3',
    tenderTitle: 'Medical Supplies Procurement',
    organization: 'Ministry of Health',
    bidAmount: 'E 1,180,000',
    status: 'Under Review',
    submittedDate: '2025-01-18',
    deadline: '2025-11-08',
    category: 'Supplies',
    imageUrl: Images.tender3,
  },
  {
    id: 'bid3',
    tenderId: '7',
    tenderTitle: 'Building Construction - New Office Complex',
    organization: 'Ministry of Public Works',
    bidAmount: 'E 8,200,000',
    status: 'Submitted',
    submittedDate: '2025-01-22',
    deadline: '2025-12-10',
    category: 'Construction',
    imageUrl: Images.tender7,
  },
  {
    id: 'bid4',
    tenderId: '2',
    tenderTitle: 'IT Infrastructure Upgrade',
    organization: 'Eswatini Revenue Authority',
    bidAmount: 'E 820,000',
    status: 'Rejected',
    submittedDate: '2025-01-15',
    deadline: '2025-11-30',
    category: 'IT Services',
    imageUrl: Images.tender2,
    rejectionReason: 'Did not meet technical specifications',
  },
  {
    id: 'bid5',
    tenderId: '9',
    tenderTitle: 'Telecommunications Network Expansion',
    organization: 'Eswatini Posts and Telecommunications',
    bidAmount: 'E 3,650,000',
    status: 'Accepted',
    submittedDate: '2025-01-10',
    deadline: '2025-12-05',
    category: 'IT Services',
    imageUrl: Images.tender9,
  },
];

export const mockInternships = [
  {
    id: '1',
    imageUrl: Images.intern1,
    industry: 'Technology',
    description: 'Development of a comprehensive enterprise resource planning system with modern technologies.',
    enquiryEmail: 'tenders@company.com',
    postedDate: '2025-01-10',
  },
  {
    id: '2',
    imageUrl: Images.intern2,
    industry: 'Manufacturing',
    description: 'Design and implementation of automated manufacturing line with IoT integration.',
    enquiryEmail: 'tenders@company.com',
    postedDate: '2025-01-05',
  },
  {
    id: '3',
    imageUrl: Images.intern3,
    industry: 'Healthcare',
    description: 'Complete hospital management system with patient records, billing, and scheduling.',
    postedDate: '2025-01-12',
  },
  {
    id: '4',
    imageUrl: Images.intern4,
    industry: 'Energy',
    description: 'Solar panel installation and grid integration for municipal buildings.',
    enquiryEmail: 'tenders@company.com',
    postedDate: '2025-01-08',
  },
  {
    id: '5',
    imageUrl: Images.intern5,
    industry: 'Agriculture',
    postedDate: '2025-01-08',
  },
  {
    id: '6',
    imageUrl: Images.intern6,
    industry: 'Education',
    description: 'Solar panel installation and grid integration for municipal buildings.',
    enquiryEmail: 'tenders@company.com',
    postedDate: '2025-01-08',
  },
  {
    id: '7',
    imageUrl: Images.intern7,
    industry: 'Engineering',
    description: 'Complete hospital management system with patient records, billing, and scheduling.',
    enquiryEmail: 'tenders@company.com',
    postedDate: '2025-01-08',
  }
];

export const mockProfiles = [
  {
    id: '1',
    name: 'Sarah Johnson',
    title: 'Senior Software Engineer',
    company: 'TechInnovate Corp',
    location: 'San Francisco, CA',
    industry: 'Technology',
    experience: '8 years',
    email: 'sarah.johnson@techinnovate.com',
    phone: '+1 (415) 555-0123',
    whatsapp: '+1 (415) 555-0123',
    acquiredSkills: ['React', 'TypeScript', 'Node.js', 'AWS', 'PostgreSQL', 'Docker'],
    innateSkills: ['Problem Solving', 'Critical Thinking', 'Leadership', 'Communication'],
    domesticSkills: ['Time Management', 'Organization', 'Multitasking'],
    achievements: [
      'Led team of 12 developers on flagship product',
      'Reduced system latency by 40%',
      'AWS Certified Solutions Architect'
    ],
    education: 'BS Computer Science, Stanford University',
    socialLinks: {
      linkedin: 'https://linkedin.com/in/sarahjohnson',
      github: 'https://github.com/sarahjohnson',
      twitter: 'https://twitter.com/sarahjohnson',
      website: 'https://sarahjohnson.dev'
    },
    avatar: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=400',
    isAvailableForWork: false
  },
  {
    id: '2',
    name: 'Michael Rodriguez',
    title: 'Manufacturing Operations Manager',
    company: 'Industrial Dynamics',
    location: 'Detroit, MI',
    industry: 'Manufacturing',
    experience: '12 years',
    email: 'michael.rodriguez@industrialdynamics.com',
    phone: '+1 (313) 555-0456',
    whatsapp: '+1 (313) 555-0456',
    acquiredSkills: ['Lean Manufacturing', 'Six Sigma', 'Quality Control', 'Supply Chain'],
    innateSkills: ['Team Leadership', 'Strategic Thinking', 'Attention to Detail'],
    domesticSkills: ['Project Management', 'Budgeting', 'Scheduling'],
    achievements: [
      'Implemented lean processes reducing waste by 25%',
      'Black Belt Six Sigma certification',
      'Managed $50M+ manufacturing operations'
    ],
    education: 'MS Industrial Engineering, University of Michigan',
    socialLinks: {
      linkedin: 'https://linkedin.com/in/michaelrodriguez',
      twitter: 'https://twitter.com/mrodriguez'
    },
    avatar: 'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=400',
    isAvailableForWork: true
  },
  {
    id: '3',
    name: 'Dr. Emily Chen',
    title: 'Clinical Research Director',
    company: 'BioPharma Solutions',
    location: 'Boston, MA',
    industry: 'Healthcare',
    experience: '15 years',
    email: 'emily.chen@biopharmasolutions.com',
    phone: '+1 (617) 555-0789',
    whatsapp: '+1 (617) 555-0789',
    acquiredSkills: ['Clinical Trials', 'FDA Regulations', 'Biostatistics', 'Protocol Development'],
    innateSkills: ['Analytical Thinking', 'Research Methodology', 'Team Management'],
    domesticSkills: ['Documentation', 'Compliance Management', 'Data Organization'],
    achievements: [
      'Led 20+ successful clinical trials',
      'Published 45+ peer-reviewed papers',
      'FDA Breakthrough Therapy designation'
    ],
    education: 'PhD Biomedical Sciences, Harvard Medical School',
    socialLinks: {
      linkedin: 'https://linkedin.com/in/emilychen',
      website: 'https://dremilychen.com'
    },
    avatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=400',
    isAvailableForWork: false
  },
  {
    id: '4',
    name: 'David Thompson',
    title: 'Financial Analyst',
    company: 'Investment Partners LLC',
    location: 'New York, NY',
    industry: 'Finance',
    experience: '6 years',
    email: 'david.thompson@investmentpartners.com',
    phone: '+1 (212) 555-0321',
    whatsapp: '+1 (212) 555-0321',
    acquiredSkills: ['Financial Modeling', 'Risk Analysis', 'Excel', 'Python', 'Bloomberg Terminal'],
    innateSkills: ['Analytical Thinking', 'Risk Assessment', 'Portfolio Management'],
    domesticSkills: ['Data Management', 'Report Writing', 'Client Communication'],
    achievements: [
      'CFA Charterholder',
      'Generated 15% alpha on managed portfolio',
      'Led M&A analysis for $2B+ deals'
    ],
    education: 'MBA Finance, Wharton School',
    socialLinks: {
      linkedin: 'https://linkedin.com/in/davidthompson',
      twitter: 'https://twitter.com/dthompsonfinance'
    },
    avatar: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=400',
    isAvailableForWork: true
  },
  {
    id: '5',
    name: 'Maria Garcia',
    title: 'Marketing Director',
    company: 'Brand Innovators',
    location: 'Miami, FL',
    industry: 'Marketing',
    experience: '10 years',
    email: 'maria.garcia@brandinnovators.com',
    phone: '+1 (305) 555-0654',
    whatsapp: '+1 (305) 555-0654',
    acquiredSkills: ['Digital Marketing', 'Brand Strategy', 'Social Media', 'Analytics'],
    innateSkills: ['Creativity', 'Strategic Thinking', 'Content Creation'],
    domesticSkills: ['Campaign Management', 'Client Relations', 'Budget Planning'],
    achievements: [
      'Increased brand awareness by 300%',
      'Google Ads certified professional',
      'Led campaigns generating $10M+ revenue'
    ],
    education: 'MBA Marketing, University of Miami',
    socialLinks: {
      linkedin: 'https://linkedin.com/in/mariagarcia',
      instagram: 'https://instagram.com/mariagarcia_marketing',
      twitter: 'https://twitter.com/mariagarcia',
      website: 'https://mariagarcia.marketing'
    },
    avatar: 'https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=400',
    isAvailableForWork: false
  },
  {
    id: '6',
    name: 'James Wilson',
    title: 'Elementary School Principal',
    company: 'Riverside Elementary',
    location: 'Seattle, WA',
    industry: 'Education',
    experience: '18 years',
    email: 'james.wilson@riversideelementary.edu',
    phone: '+1 (206) 555-0987',
    whatsapp: '+1 (206) 555-0987',
    acquiredSkills: ['Educational Leadership', 'Curriculum Development', 'Teacher Training'],
    innateSkills: ['Leadership', 'Communication', 'Student Assessment'],
    domesticSkills: ['Administrative Management', 'Event Planning', 'Community Outreach'],
    achievements: [
      'Improved school test scores by 40%',
      'Principal of the Year Award 2023',
      'Implemented innovative STEM program'
    ],
    education: 'EdD Educational Leadership, University of Washington',
    socialLinks: {
      linkedin: 'https://linkedin.com/in/jameswilson',
      twitter: 'https://twitter.com/principalwilson'
    },
    avatar: 'https://images.pexels.com/photos/1043471/pexels-photo-1043471.jpeg?auto=compress&cs=tinysrgb&w=400',
    isAvailableForWork: true
  },
  {
    id: '7',
    name: 'Lisa Park',
    title: 'Renewable Energy Engineer',
    company: 'SolarTech Solutions',
    location: 'Phoenix, AZ',
    industry: 'Energy',
    experience: '7 years',
    email: 'lisa.park@solartech.com',
    phone: '+1 (602) 555-0147',
    whatsapp: '+1 (602) 555-0147',
    acquiredSkills: ['Solar Design', 'Grid Integration', 'Energy Storage', 'Project Management'],
    innateSkills: ['Problem Solving', 'Innovation', 'Sustainability Thinking'],
    domesticSkills: ['Technical Documentation', 'Client Presentations', 'Regulatory Compliance'],
    achievements: [
      'Designed 50+ MW solar installations',
      'NABCEP certified solar professional',
      'Reduced project costs by 20%'
    ],
    education: 'MS Renewable Energy Engineering, Arizona State University',
    socialLinks: {
      linkedin: 'https://linkedin.com/in/lisapark',
      github: 'https://github.com/lisapark',
      website: 'https://lisapark.energy'
    },
    avatar: 'https://images.pexels.com/photos/1181424/pexels-photo-1181424.jpeg?auto=compress&cs=tinysrgb&w=400',
    isAvailableForWork: false
  },
  {
    id: '8',
    name: 'Robert Brown',
    title: 'Agricultural Specialist',
    company: 'FarmTech Innovations',
    location: 'Des Moines, IA',
    industry: 'Agriculture',
    experience: '14 years',
    email: 'robert.brown@farmtech.com',
    phone: '+1 (515) 555-0258',
    whatsapp: '+1 (515) 555-0258',
    acquiredSkills: ['Crop Management', 'Precision Agriculture', 'Soil Science', 'Irrigation Systems'],
    innateSkills: ['Data Analysis', 'Environmental Awareness', 'Innovation'],
    domesticSkills: ['Farm Management', 'Equipment Maintenance', 'Record Keeping'],
    achievements: [
      'Increased crop yields by 35%',
      'Certified Crop Advisor',
      'Pioneered drone-based crop monitoring'
    ],
    education: 'MS Agronomy, Iowa State University',
    socialLinks: {
      linkedin: 'https://linkedin.com/in/robertbrown',
      twitter: 'https://twitter.com/agritech_rob'
    },
    avatar: 'https://images.pexels.com/photos/1212984/pexels-photo-1212984.jpeg?auto=compress&cs=tinysrgb&w=400',
    isAvailableForWork: true
  }
];

export const allIndustries = [
  'Technology',
  'Healthcare',
  'Finance',
  'Manufacturing',
  'Education',
  'Marketing',
  'Energy',
  'Agriculture',
  'Construction',
  'Transportation',
  'Retail',
  'Hospitality',
  'Real Estate',
  'Legal',
  'Consulting',
  'Media',
  'Telecommunications',
  'Automotive',
  'Aerospace',
  'Biotechnology',
  'Pharmaceuticals',
  'Food & Beverage',
  'Fashion',
  'Sports',
  'Non-profit',
  'Government',
  'Insurance',
  'Banking',
  'Entertainment',
  'Gaming',
  'Other'
];

// Supply Chain
export const mockVendors = [
  {
    id: '1',
    name: 'Thabo\'s Fresh Vegetables',
    type: 'Street Vendor',
    category: 'Vegetables',
    description: 'Fresh vegetables from local farms',
    location: {
      latitude: -26.3051,
      longitude: 31.1367,
      address: 'Mbabane Market Square',
      area: 'Mbabane'
    },
    contact: {
      phone: '+268 2400 1234',
      whatsapp: '+268 2400 1234'
    },
    workingHours: {
      monday: '06:00-18:00',
      tuesday: '06:00-18:00',
      wednesday: '06:00-18:00',
      thursday: '06:00-18:00',
      friday: '06:00-18:00',
      saturday: '06:00-14:00',
      sunday: 'Closed'
    },
    rating: 4.5,
    reviewCount: 23,
    deliveryRadius: 5,
    isOnline: true,
    joinedDate: '2023-01-15',
    profileImage: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=400',
    stock: [
      { item: 'Tomatoes', price: 15, unit: 'per kg', available: true },
      { item: 'Onions', price: 12, unit: 'per kg', available: true },
      { item: 'Carrots', price: 18, unit: 'per kg', available: false }
    ]
  },
  {
    id: '2',
    name: 'Sipho\'s Mobile Kitchen',
    type: 'Street Vendor',
    category: 'Food & Beverages',
    description: 'Traditional Swazi meals and snacks',
    location: {
      latitude: -26.3186,
      longitude: 31.1417,
      address: 'Manzini Industrial Area',
      area: 'Manzini'
    },
    contact: {
      phone: '+268 2505 5678',
      whatsapp: '+268 2505 5678'
    },
    workingHours: {
      monday: '07:00-19:00',
      tuesday: '07:00-19:00',
      wednesday: '07:00-19:00',
      thursday: '07:00-19:00',
      friday: '07:00-19:00',
      saturday: '08:00-15:00',
      sunday: 'Closed'
    },
    rating: 4.8,
    reviewCount: 45,
    deliveryRadius: 8,
    isOnline: true,
    joinedDate: '2023-02-20',
    profileImage: 'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=400',
    stock: [
      { item: 'Traditional Stew', price: 35, unit: 'per plate', available: true },
      { item: 'Fresh Bread', price: 8, unit: 'per loaf', available: true },
      { item: 'Local Tea', price: 5, unit: 'per cup', available: true }
    ]
  },
  {
    id: '3',
    name: 'Nomsa\'s Craft Shop',
    type: 'Small Shop',
    category: 'Handicrafts',
    description: 'Traditional Swazi crafts and souvenirs',
    location: {
      latitude: -26.3051,
      longitude: 31.1367,
      address: 'Ezulwini Valley',
      area: 'Ezulwini'
    },
    contact: {
      phone: '+268 2416 9012',
      whatsapp: '+268 2416 9012'
    },
    workingHours: {
      monday: '09:00-17:00',
      tuesday: '09:00-17:00',
      wednesday: '09:00-17:00',
      thursday: '09:00-17:00',
      friday: '09:00-17:00',
      saturday: '09:00-16:00',
      sunday: '10:00-14:00'
    },
    rating: 4.2,
    reviewCount: 18,
    deliveryRadius: 15,
    isOnline: false,
    joinedDate: '2023-03-10',
    profileImage: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=400',
    stock: [
      { item: 'Traditional Baskets', price: 120, unit: 'each', available: true },
      { item: 'Wooden Carvings', price: 80, unit: 'each', available: true },
      { item: 'Beaded Jewelry', price: 45, unit: 'each', available: false }
    ]
  }
];

export const mockBulkGroups = [
  {
    id: '1',
    name: 'Mbabane Vegetable Collective',
    category: 'Vegetables',
    description: 'Bulk buying group for fresh vegetables',
    leader: 'Thabo Dlamini',
    memberCount: 12,
    minOrder: 500,
    savings: 15,
    nextOrderDate: '2024-01-15',
    area: 'Mbabane',
    requirements: 'Minimum 6 months business operation',
    benefits: ['15% bulk discount', 'Weekly delivery', 'Quality guarantee']
  },
  {
    id: '2',
    name: 'Manzini Food Suppliers',
    category: 'Food & Beverages',
    description: 'Bulk purchasing for food vendors',
    leader: 'Sipho Mamba',
    memberCount: 8,
    minOrder: 800,
    savings: 20,
    nextOrderDate: '2024-01-20',
    area: 'Manzini',
    requirements: 'Valid business license required',
    benefits: ['20% bulk discount', 'Bi-weekly delivery', 'Freshness guarantee']
  }
];

export const mockSuppliers = [
  {
    id: '1',
    name: 'Swazi Fresh Produce Co.',
    type: 'Wholesale',
    category: 'Vegetables',
    description: 'Large-scale supplier of fresh vegetables and fruits from local farms.',
    logo: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400',
    contact: {
      phone: '+268 2528 3456',
      email: 'info@swazifreshproduce.com',
      whatsapp: '+268 2528 3456',
    },
    location: 'Malkerns',
    minOrder: 1000,
    deliveryAreas: ['Mbabane', 'Manzini', 'Ezulwini'],
    products: ['Fresh Vegetables', 'Herbs', 'Fruits'],
    marketingInfo: 'Committed to delivering farm-fresh produce with reliable delivery across major towns.',
    deals: [
      {
        id: 'sd1',
        title: 'Bulk Veggie Deal',
        desc: '15% off orders over SZL 2000',
        image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400',
      },
      {
        id: 'sd2',
        title: 'Free Delivery',
        desc: 'Free delivery on orders over SZL 1500',
        image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3a8dd22?w=400',
      },
    ],
    rating: 4.6,
    reviewCount: 50,
  },
  {
    id: '2',
    name: 'Royal Swazi Foods',
    type: 'Manufacturer',
    category: 'Processed Foods',
    description: 'Leading manufacturer of traditional Swazi foods and snacks.',
    logo: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=400',
    contact: {
      phone: '+268 2518 7890',
      email: 'sales@royalswazifoods.com',
      whatsapp: '+268 2518 7890',
    },
    location: 'Matsapha',
    minOrder: 500,
    deliveryAreas: ['All major towns'],
    products: ['Traditional Foods', 'Snacks', 'Beverages'],
    marketingInfo: 'Authentic Swazi flavors crafted with quality ingredients for local and regional markets.',
    deals: [
      {
        id: 'sd3',
        title: 'Snack Combo Offer',
        desc: 'Buy 2 snack packs, get 1 free',
        image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=400',
      },
      {
        id: 'sd4',
        title: 'Bulk Beverage Deal',
        desc: '10% off beverage orders over SZL 1000',
        image: 'https://images.unsplash.com/photo-1604908177079-46b0f84b39c8?w=400',
      },
    ],
    rating: 4.2,
    reviewCount: 35,
  },
  {
    id: '3',
    name: 'Philas Stop Shop',
    type: 'Retailer',
    category: 'Food & Beverages',
    description: 'Timely supply with fast foods to Manzini locals.',
    logo: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=400',
    contact: {
      phone: '+268 2518 7890',
      email: 'hotfoods@philastopshop.com',
      whatsapp: '+268 2518 7890',
    },
    location: 'Fair View',
    minOrder: 500,
    deliveryAreas: ['Fair View', 'Bus Rank', 'Nazarene', 'Ka-Khoza'],
    products: ['Traditional Foods', 'Snacks', 'Beverages'],
    marketingInfo: 'Authentic Swazi flavors crafted with quality ingredients for local and regional markets.',
    deals: [
      {
        id: 'sd3',
        title: 'Snack Combo Offer',
        desc: 'Buy 2 snack packs, get 1 free',
        image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=400',
      },
      {
        id: 'sd4',
        title: 'Bulk Beverage Deal',
        desc: '10% off beverage orders over SZL 1000',
        image: 'https://images.unsplash.com/photo-1604908177079-46b0f84b39c8?w=400',
      },
    ],
    rating: 4.2,
    reviewCount: 35,
  },
  {
    id: '4',
    name: 'Season Crafts',
    type: 'Manufacturer',
    category: 'Crafted',
    description: 'Leading manufacturer of traditional Swazi hand made crafts.',
    logo: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=400',
    contact: {
      phone: '+268 2518 7890',
      email: 'swazistyle@seasoncrafts.com',
      whatsapp: '+268 2518 7890',
    },
    location: 'Madlangemphisi',
    minOrder: 200,
    deliveryAreas: ['Manzini', 'Matsapha', 'Mkhondvo', 'Mantenga'],
    products: ['Swazi Crafts', 'Wooden Ornaments', 'Swazi Beads'],
    marketingInfo: 'Authentic Swazi crafted ornaments with quality traditional materials for local and regional markets.',
    deals: [
      {
        id: 'sd3',
        title: 'Snack Combo Offer',
        desc: 'Buy 2 snack packs, get 1 free',
        image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=400',
      },
      {
        id: 'sd4',
        title: 'Bulk Beverage Deal',
        desc: '10% off beverage orders over SZL 1000',
        image: 'https://images.unsplash.com/photo-1604908177079-46b0f84b39c8?w=400',
      },
    ],
    rating: 4.2,
    reviewCount: 35,
  },
];

export const mockSupplierAdverts = [
  {
    id: 'ad-1',
    title: 'Combo A',
    desc: 'Rice + Oil + Sugar',
    image: 'https://images.unsplash.com/photo-1604908177079-46b0f84b39c8?w=1200'
  },
  {
    id: 'ad-2',
    title: 'Combo B',
    desc: 'Flour + Beans',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31b?w=1200'
  },
  {
    id: 'ad-3',
    title: '10% off Cooking Oil',
    desc: 'Limited time deal',
    image: 'https://images.unsplash.com/photo-1585238342028-4bbc2c23c2d5?w=1200'
  }
];

export const mockBrokers = [
  {
    id: 'b1',
    name: 'Industry Broker A',
    specialty: 'Agriculture, Logistics',
    description: 'Matching farmers with distributors for efficient supply chain solutions.',
    logo: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=400',
    contact: {
      phone: '+268 2400 1234',
      email: 'contact@industrybrokera.com',
      whatsapp: '+268 2400 1234',
    },
    location: 'Mbabane',
    marketingInfo: 'Trusted partner for over 200 farmers, offering seamless logistics and distribution services.',
    deals: [
      { id: 'd1', title: 'Logistics Discount', desc: '20% off transport costs for bulk orders', image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3a8dd22?w=400' },
      { id: 'd2', title: 'Free Consultation', desc: 'Free supply chain analysis for new clients', image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400' },
    ],
    rating: 4.7,
    reviewCount: 30,
  },
  {
    id: 'b2',
    name: 'Intermediary B',
    specialty: 'Manufacturing, Packaging',
    description: 'Sourcing high-quality packaging solutions for small and medium enterprises.',
    logo: 'https://images.unsplash.com/photo-1587613864414-6a9e8d5296ca?w=400',
    contact: {
      phone: '+268 2505 5678',
      email: 'info@intermediaryb.com',
      whatsapp: '+268 2505 5678',
    },
    location: 'Manzini',
    marketingInfo: 'Specialized in eco-friendly packaging with a network of trusted manufacturers.',
    deals: [
      {
        id: 'd3', title: 'Eco-Pack Deal', desc: '10% off biodegradable packaging',
        image: 'https://images.unsplash.com/photo-1581579185617-3f072e5d3690?w=400'
      },
    ],
    rating: 4.5,
    reviewCount: 25,
  },
  {
    id: 'b3',
    name: 'Trade Link C',
    specialty: 'Import/Export',
    description: 'Facilitating cross-border shipments and customs clearance.',
    logo: 'https://images.unsplash.com/photo-1567427013953-1c0e560fbf19?w=400',
    contact: {
      phone: '+268 2416 9012',
      email: 'support@tradelinkc.com',
      whatsapp: '+268 2416 9012',
    },
    location: 'Matsapha',
    marketingInfo: 'Streamlined import/export services with a focus on compliance and efficiency.',
    deals: [
      {
        id: 'd4', title: 'Customs Fast-Track', desc: 'Priority customs clearance for urgent shipments',
        image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=400'
      },
    ],
    rating: 4.8,
    reviewCount: 40,
  },
];

export const mockFinanceOffers = [
  {
    id: 'f1',
    name: 'Eswatini Bank',
    offer: 'SME Loans, 12% APR',
    description: 'Flexible financing solutions for small and medium enterprises.',
    logo: 'https://images.unsplash.com/photo-1553729459-efe14ef6055d?w=400',
    contact: {
      phone: '+268 2404 5678',
      email: 'loans@eswatinibank.com',
      whatsapp: '+268 2404 5678',
    },
    location: 'Mbabane',
    marketingInfo: 'Empowering businesses with tailored financial products and dedicated support.',
    deals: [
      { id: 'fd1', title: 'SME Loan Offer', desc: 'Low-interest loans up to SZL 500,000', image: 'https://images.unsplash.com/photo-1556745753-b2904692b3cd?w=400' },
      { id: 'fd2', title: 'No-Fee Accounts', desc: 'Free business account setup for new clients', image: 'https://images.unsplash.com/photo-1567427013953-1c0e560fbf19?w=400' },
    ],
    rating: 4.6,
    reviewCount: 50,
  },
  {
    id: 'f2',
    name: 'Building Society',
    offer: 'Micro-loans up to SZL 20,000',
    description: 'Quick and easy micro-loans for small businesses and entrepreneurs.',
    logo: 'https://images.unsplash.com/photo-1567427013953-1c0e560fbf19?w=400',
    contact: {
      phone: '+268 2518 7890',
      email: 'info@buildingsociety.com',
      whatsapp: '+268 2518 7890',
    },
    location: 'Manzini',
    marketingInfo: 'Supporting small businesses with accessible financing and low rates.',
    deals: [
      { id: 'fd3', title: 'Micro-Loan Promo', desc: 'No repayment for first 3 months', image: 'https://images.unsplash.com/photo-1556745753-b2904692b3cd?w=400' },
    ],
    rating: 4.3,
    reviewCount: 35,
  },
  {
    id: 'f3',
    name: 'InstaCash',
    offer: 'POS machines, 0% setup fee',
    description: 'Modern payment solutions for businesses of all sizes.',
    logo: 'https://images.unsplash.com/photo-1556745753-b2904692b3cd?w=400',
    contact: {
      phone: '+268 2528 3456',
      email: 'support@instacash.com',
      whatsapp: '+268 2528 3456',
    },
    location: 'Ezulwini',
    marketingInfo: 'Seamless payment processing with cutting-edge POS technology.',
    deals: [
      { id: 'fd4', title: 'Free POS Setup', desc: 'Zero setup fees for new POS systems', image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3a8dd22?w=400' },
    ],
    rating: 4.9,
    reviewCount: 60,
  },
];

export const mockCustomers = [
  {
    id: '1',
    name: 'John Mkhonta',
    type: 'Employee',
    location: 'Mbabane Industrial Area',
    preferences: ['Vegetables', 'Traditional Foods'],
    orderHistory: [
      { vendorId: '1', items: ['Tomatoes', 'Onions'], total: 27, date: '2024-01-10' },
      { vendorId: '2', items: ['Traditional Stew'], total: 35, date: '2024-01-08' }
    ]
  },
  {
    id: '2',
    name: 'Sarah Ndlovu',
    type: 'Individual',
    location: 'Ezulwini Valley',
    preferences: ['Handicrafts', 'Organic Vegetables'],
    orderHistory: [
      { vendorId: '3', items: ['Traditional Baskets'], total: 120, date: '2024-01-12' }
    ]
  }
];

export const mockOrders = [
  {
    id: '1',
    customerId: '1',
    vendorId: '1',
    items: [
      { name: 'Tomatoes', quantity: 2, price: 15, unit: 'kg' },
      { name: 'Onions', quantity: 1, price: 12, unit: 'kg' }
    ],
    total: 42,
    status: 'delivered',
    orderDate: '2024-01-10',
    deliveryDate: '2024-01-10',
    deliveryAddress: 'Mbabane Industrial Area, Building A'
  },
  {
    id: '2',
    customerId: '2',
    vendorId: '2',
    items: [
      { name: 'Traditional Stew', quantity: 2, price: 35, unit: 'plate' }
    ],
    total: 70,
    status: 'in_progress',
    orderDate: '2024-01-14',
    estimatedDelivery: '2024-01-14 12:30',
    deliveryAddress: 'Ezulwini Valley, House 123'
  }
];

export const mockCategories = [
  { id: '1', name: 'Tilimo', icon: '🥬', color: '#4CAF50' },
  { id: '2', name: 'Food & Beverages', icon: '🍲', color: '#FF9800' },
  { id: '3', name: 'Handicrafts', icon: '🎨', color: '#9C27B0' },
  { id: '4', name: 'Electronics', icon: '📱', color: '#2196F3' },
  { id: '5', name: 'Clothing', icon: '👕', color: '#E91E63' },
  { id: '6', name: 'Home & Garden', icon: '🏠', color: '#795548' }
];

export const mockAreas = [
  'Mbabane', 'Manzini', 'Ezulwini', 'Malkerns', 'Matsapha', 'Big Bend', 'Nhlangano', 'Siteki'
];

// Rental Houses Mock Data
export const mockRentalHouses = [
  {
    id: 'rh1',
    title: 'Spacious 3-Bedroom House in Mbabane',
    type: 'house', // 'house', 'apartment', 'room', 'flat'
    images: [
      'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800',
      'https://images.unsplash.com/photo-1568605117032-4c0c0c0c0c0?w=800',
      'https://images.unsplash.com/photo-1568605117032-4c0c0c0c0c1?w=800',
    ],
    price: 4500,
    currency: 'SZL',
    area: 'Mbabane',
    city: 'Mbabane',
    village: null,
    township: 'Hilltop',
    address: '45 Somhlolo Street, Hilltop, Mbabane',
    bedrooms: 3,
    bathrooms: 2,
    size: 120, // square meters
    available: true,
    availableDate: '2025-02-01',
    description: 'Beautiful spacious house with modern amenities, perfect for families. Located in a quiet neighborhood with easy access to schools and shopping centers.',
    amenities: [
      'Fully Furnished',
      'Parking Space',
      'Garden',
      'Security System',
      'Water & Electricity',
      'WiFi Ready',
      'Near Schools',
      'Shopping Nearby',
    ],
    rules: [
      'No smoking inside',
      'No pets allowed',
      'Maximum 4 occupants',
      'Quiet hours after 10 PM',
      'Monthly rent due on 1st',
      '1 month deposit required',
    ],
    requirements: [
      'Employment letter or proof of income',
      'ID copy',
      '2 references',
      'Credit check',
      'Deposit: 1 month rent',
    ],
    landlord: {
      name: 'Thabo Dlamini',
      phone: '+268 2404 1234',
      email: 'thabo.dlamini@email.com',
      whatsapp: '+268 2404 1234',
      verified: true,
      rating: 4.8,
      responseTime: 'Within 24 hours',
    },
    postedDate: '2025-01-15',
    views: 245,
    applications: 8,
    status: 'available',
  },
  {
    id: 'rh2',
    title: 'Modern 2-Bedroom Apartment in Manzini',
    type: 'apartment',
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0268?w=800',
    ],
    price: 3200,
    currency: 'SZL',
    area: 'Manzini',
    city: 'Manzini',
    village: null,
    township: 'Fairview',
    address: '12 Industrial Road, Fairview, Manzini',
    bedrooms: 2,
    bathrooms: 1,
    size: 75,
    available: true,
    availableDate: '2025-02-15',
    description: 'Modern apartment in the heart of Manzini. Close to business district and public transport.',
    amenities: [
      'Fully Furnished',
      'Parking Space',
      'Security Guard',
      'Water & Electricity',
      'WiFi Included',
      'Gym Access',
    ],
    rules: [
      'No smoking',
      'No pets',
      'Maximum 2 occupants',
      'No parties',
    ],
    requirements: [
      'Proof of income',
      'ID copy',
      '1 month deposit',
    ],
    landlord: {
      name: 'Sarah Mamba',
      phone: '+268 2505 5678',
      email: 'sarah.mamba@email.com',
      whatsapp: '+268 2505 5678',
      verified: true,
      rating: 4.6,
      responseTime: 'Within 12 hours',
    },
    postedDate: '2025-01-20',
    views: 189,
    applications: 5,
    status: 'available',
  },
  {
    id: 'rh3',
    title: 'Cozy Single Room in Shared House',
    type: 'room',
    images: [
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800',
    ],
    price: 1200,
    currency: 'SZL',
    area: 'Ezulwini',
    city: 'Ezulwini',
    village: 'Ezulwini Valley',
    township: null,
    address: '8 Valley Road, Ezulwini Valley',
    bedrooms: 1,
    bathrooms: 1, // shared
    size: 15,
    available: true,
    availableDate: '2025-01-25',
    description: 'Single room in a shared house. Shared kitchen and bathroom. Perfect for students or working professionals.',
    amenities: [
      'Furnished Room',
      'Shared Kitchen',
      'Shared Bathroom',
      'WiFi Included',
      'Water & Electricity',
      'Security',
    ],
    rules: [
      'Respect shared spaces',
      'No overnight guests',
      'Keep common areas clean',
      'No smoking',
    ],
    requirements: [
      'ID copy',
      'Proof of income or student ID',
      '1 month deposit',
    ],
    landlord: {
      name: 'Nomsa Ndlovu',
      phone: '+268 2416 9012',
      email: 'nomsa.ndlovu@email.com',
      whatsapp: '+268 2416 9012',
      verified: false,
      rating: 4.4,
      responseTime: 'Within 48 hours',
    },
    postedDate: '2025-01-18',
    views: 156,
    applications: 12,
    status: 'available',
  },
  {
    id: 'rh4',
    title: 'Luxury 4-Bedroom Flat in Mbabane',
    type: 'flat',
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c751?w=800',
    ],
    price: 6800,
    currency: 'SZL',
    area: 'Mbabane',
    city: 'Mbabane',
    village: null,
    township: 'The Gables',
    address: '23 Gables Road, The Gables, Mbabane',
    bedrooms: 4,
    bathrooms: 3,
    size: 180,
    available: true,
    availableDate: '2025-03-01',
    description: 'Luxury flat with modern finishes, spacious rooms, and premium amenities. Ideal for professionals or large families.',
    amenities: [
      'Fully Furnished',
      '2 Parking Spaces',
      'Swimming Pool',
      'Gym',
      'Security System',
      'Water & Electricity',
      'WiFi Ready',
      'Balcony',
      'Near Shopping Mall',
    ],
    rules: [
      'No smoking',
      'Pets allowed (with deposit)',
      'Maximum 6 occupants',
      'No loud music',
      'Monthly rent due on 1st',
      '2 months deposit required',
    ],
    requirements: [
      'Employment letter',
      'ID copy',
      '3 references',
      'Credit check',
      'Deposit: 2 months rent',
      'Proof of income (3x rent)',
    ],
    landlord: {
      name: 'Property Management Co.',
      phone: '+268 2404 9999',
      email: 'info@propertymgmt.co.sz',
      whatsapp: '+268 2404 9999',
      verified: true,
      rating: 4.9,
      responseTime: 'Within 6 hours',
    },
    postedDate: '2025-01-10',
    views: 432,
    applications: 15,
    status: 'available',
  },
  {
    id: 'rh5',
    title: 'Affordable 1-Bedroom in Nhlangano',
    type: 'apartment',
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
    ],
    price: 1800,
    currency: 'SZL',
    area: 'Nhlangano',
    city: 'Nhlangano',
    village: null,
    township: 'Town Center',
    address: '5 Main Street, Town Center, Nhlangano',
    bedrooms: 1,
    bathrooms: 1,
    size: 45,
    available: true,
    availableDate: '2025-02-10',
    description: 'Affordable one-bedroom apartment in Nhlangano town center. Perfect for individuals or couples.',
    amenities: [
      'Semi-Furnished',
      'Parking Available',
      'Water & Electricity',
      'Security',
    ],
    rules: [
      'No smoking',
      'No pets',
      'Maximum 2 occupants',
    ],
    requirements: [
      'ID copy',
      'Proof of income',
      '1 month deposit',
    ],
    landlord: {
      name: 'Sipho Khumalo',
      phone: '+268 2528 3456',
      email: 'sipho.khumalo@email.com',
      whatsapp: '+268 2528 3456',
      verified: false,
      rating: 4.2,
      responseTime: 'Within 24 hours',
    },
    postedDate: '2025-01-22',
    views: 98,
    applications: 3,
    status: 'available',
  },
];

// Lease Items Mock Data (for borrowing/leasing items)
export const mockLeaseItems = [
  {
    id: 'li1',
    title: 'Professional Camera Equipment Set',
    category: 'Electronics',
    subcategory: 'Photography',
    images: [
      'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800',
      'https://images.unsplash.com/photo-1516035069371-29a1b244cc33?w=800',
    ],
    price: 500, // per day
    currency: 'SZL',
    deposit: 2000,
    location: {
      area: 'Mbabane',
      city: 'Mbabane',
      village: null,
      township: 'Hilltop',
      address: 'Mbabane, Hilltop',
    },
    description: 'Complete professional camera set including DSLR, lenses, tripod, and lighting equipment. Perfect for events, weddings, or professional photography.',
    condition: 'Excellent',
    available: true,
    availableFrom: '2025-01-25',
    availableTo: '2025-12-31',
    leaseType: 'daily', // 'daily', 'weekly', 'monthly'
    owner: {
      name: 'Photography Pro',
      phone: '+268 2404 1111',
      email: 'rent@photographypro.sz',
      whatsapp: '+268 2404 1111',
      verified: true,
      rating: 4.9,
      responseTime: 'Within 2 hours',
    },
    requirements: [
      'Valid ID',
      'Deposit required',
      'Return in same condition',
      'Insurance recommended',
    ],
    rules: [
      'Handle with care',
      'No modifications',
      'Return by agreed time',
      'Report any damages immediately',
    ],
    postedDate: '2025-01-15',
    views: 156,
    applications: 4,
    status: 'available',
  },
  {
    id: 'li2',
    title: 'Power Tools Set - Construction Equipment',
    category: 'Tools',
    subcategory: 'Construction',
    images: [
      'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=800',
    ],
    price: 300, // per day
    currency: 'SZL',
    deposit: 1500,
    location: {
      area: 'Manzini',
      city: 'Manzini',
      village: null,
      township: 'Industrial Area',
      address: 'Manzini, Industrial Area',
    },
    description: 'Complete set of power tools including drill, saw, grinder, and accessories. Ideal for construction projects.',
    condition: 'Good',
    available: true,
    availableFrom: '2025-01-20',
    availableTo: null,
    leaseType: 'daily',
    owner: {
      name: 'Construction Tools Rental',
      phone: '+268 2505 2222',
      email: 'tools@construction.sz',
      whatsapp: '+268 2505 2222',
      verified: true,
      rating: 4.7,
      responseTime: 'Within 4 hours',
    },
    requirements: [
      'Valid ID',
      'Deposit required',
      'Proof of project (optional)',
    ],
    rules: [
      'Use safety equipment',
      'Return cleaned',
      'Report damages',
    ],
    postedDate: '2025-01-18',
    views: 89,
    applications: 2,
    status: 'available',
  },
  {
    id: 'li3',
    title: 'Designer Wedding Dress Collection',
    category: 'Fashion',
    subcategory: 'Wedding',
    images: [
      'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=800',
    ],
    price: 800, // per day
    currency: 'SZL',
    deposit: 3000,
    location: {
      area: 'Mbabane',
      city: 'Mbabane',
      village: null,
      township: 'The Gables',
      address: 'Mbabane, The Gables',
    },
    description: 'Beautiful collection of designer wedding dresses in various sizes. Perfect for your special day.',
    condition: 'Excellent',
    available: true,
    availableFrom: '2025-02-01',
    availableTo: null,
    leaseType: 'daily',
    owner: {
      name: 'Bridal Boutique',
      phone: '+268 2404 3333',
      email: 'dresses@bridalboutique.sz',
      whatsapp: '+268 2404 3333',
      verified: true,
      rating: 4.8,
      responseTime: 'Within 6 hours',
    },
    requirements: [
      'Valid ID',
      'Deposit required',
      'Size fitting required',
      'Dry cleaning after use',
    ],
    rules: [
      'Handle with extreme care',
      'No alterations',
      'Return cleaned',
      'No smoking near dress',
    ],
    postedDate: '2025-01-12',
    views: 234,
    applications: 7,
    status: 'available',
  },
  {
    id: 'li4',
    title: 'Farm Equipment - Tractor & Implements',
    category: 'Agriculture',
    subcategory: 'Farm Equipment',
    images: [
      'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=800',
    ],
    price: 2000, // per day
    currency: 'SZL',
    deposit: 10000,
    location: {
      area: 'Malkerns',
      city: null,
      village: 'Malkerns',
      township: null,
      address: 'Malkerns, Eswatini',
    },
    description: 'Farm tractor with plowing and harvesting implements. Perfect for large-scale farming operations.',
    condition: 'Good',
    available: true,
    availableFrom: '2025-02-15',
    availableTo: '2025-05-30',
    leaseType: 'daily',
    owner: {
      name: 'Agricultural Services',
      phone: '+268 2528 4444',
      email: 'farm@agriservices.sz',
      whatsapp: '+268 2528 4444',
      verified: true,
      rating: 4.6,
      responseTime: 'Within 24 hours',
    },
    requirements: [
      'Valid ID',
      'Deposit required',
      'Valid driver\'s license',
      'Proof of farming activity',
    ],
    rules: [
      'Operate safely',
      'Return cleaned',
      'Report any issues',
      'Fuel not included',
    ],
    postedDate: '2025-01-08',
    views: 67,
    applications: 1,
    status: 'available',
  },
  {
    id: 'li5',
    title: 'Home Appliances - Washing Machine & Dryer',
    category: 'Appliances',
    subcategory: 'Home',
    images: [
      'https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800',
    ],
    price: 150, // per day
    currency: 'SZL',
    deposit: 800,
    location: {
      area: 'Manzini',
      city: 'Manzini',
      village: null,
      township: 'Fairview',
      address: 'Manzini, Fairview',
    },
    description: 'High-quality washing machine and dryer set. Perfect for temporary use or events.',
    condition: 'Excellent',
    available: true,
    availableFrom: '2025-01-20',
    availableTo: null,
    leaseType: 'daily',
    owner: {
      name: 'Home Appliance Rentals',
      phone: '+268 2505 5555',
      email: 'appliances@home.sz',
      whatsapp: '+268 2505 5555',
      verified: false,
      rating: 4.5,
      responseTime: 'Within 12 hours',
    },
    requirements: [
      'Valid ID',
      'Deposit required',
    ],
    rules: [
      'Use properly',
      'Return cleaned',
      'Report damages',
    ],
    postedDate: '2025-01-19',
    views: 123,
    applications: 3,
    status: 'available',
  },
  {
    id: 'li6',
    title: 'Power Drill Set - Professional Grade',
    category: 'Tools',
    subcategory: 'Power Tools',
    images: [
      'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=800',
    ],
    price: 150,
    currency: 'SZL',
    deposit: 500,
    location: {
      area: 'Mbabane',
      city: 'Mbabane',
      village: null,
      township: 'Industrial Area',
      address: 'Mbabane, Industrial Area',
    },
    description: 'Professional power drill set with multiple bits and accessories. Perfect for construction and DIY projects.',
    condition: 'Excellent',
    available: true,
    availableFrom: '2025-01-20',
    availableTo: '2025-12-31',
    leaseType: 'daily',
    owner: {
      name: 'Tool Rental Services',
      phone: '+268 2404 8888',
      email: 'tools@rental.sz',
      whatsapp: '+268 2404 8888',
      verified: true,
      rating: 4.7,
      responseTime: 'Within 4 hours',
    },
    requirements: [
      'Valid ID',
      'Deposit required',
    ],
    rules: [
      'Handle with care',
      'Return in same condition',
    ],
    postedDate: '2025-01-20',
    views: 89,
    applications: 3,
    status: 'available',
  },
  {
    id: 'li7',
    title: 'Farm Land for Lease - 50 Hectares',
    category: 'Agriculture',
    subcategory: 'Farm Land',
    images: [
      'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=800',
    ],
    price: 5000,
    currency: 'SZL',
    deposit: 10000,
    location: {
      area: 'Malkerns',
      city: null,
      village: 'Malkerns',
      township: null,
      address: 'Malkerns, Eswatini',
    },
    description: 'Large farm land suitable for crop cultivation. Includes water access and storage facilities.',
    condition: 'Good',
    available: true,
    availableFrom: '2025-03-01',
    availableTo: '2025-12-31',
    leaseType: 'monthly',
    owner: {
      name: 'Agricultural Land Services',
      phone: '+268 2528 5555',
      email: 'land@agriservices.sz',
      whatsapp: '+268 2528 5555',
      verified: true,
      rating: 4.8,
      responseTime: 'Within 24 hours',
    },
    requirements: [
      'Valid ID',
      'Deposit required',
      'Farming experience preferred',
    ],
    rules: [
      'Maintain land condition',
      'No permanent structures',
      'Follow agricultural guidelines',
    ],
    postedDate: '2025-01-10',
    views: 234,
    applications: 12,
    status: 'available',
  },
  {
    id: 'li8',
    title: 'Welding Equipment Set',
    category: 'Tools',
    subcategory: 'Welding Tools',
    images: [
      'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800',
    ],
    price: 300,
    currency: 'SZL',
    deposit: 1000,
    location: {
      area: 'Manzini',
      city: 'Manzini',
      village: null,
      township: 'Industrial Area',
      address: 'Manzini, Industrial Area',
    },
    description: 'Complete welding equipment set including welder, safety gear, and accessories.',
    condition: 'Good',
    available: true,
    availableFrom: '2025-01-25',
    availableTo: '2025-12-31',
    leaseType: 'daily',
    owner: {
      name: 'Industrial Tools Rental',
      phone: '+268 2505 9999',
      email: 'industrial@tools.sz',
      whatsapp: '+268 2505 9999',
      verified: true,
      rating: 4.6,
      responseTime: 'Within 6 hours',
    },
    requirements: [
      'Valid ID',
      'Deposit required',
      'Safety training certificate preferred',
    ],
    rules: [
      'Use safety equipment',
      'Return cleaned',
      'Report any issues',
    ],
    postedDate: '2025-01-25',
    views: 112,
    applications: 5,
    status: 'available',
  },
];

// Rental Applications Mock Data
export const mockRentalApplications = [
  {
    id: 'app1',
    houseId: 'rh1',
    houseTitle: 'Spacious 3-Bedroom House in Mbabane',
    applicantName: 'John Mkhonta',
    applicantEmail: 'john.mkhonta@email.com',
    applicantPhone: '+268 2404 7777',
    appliedDate: '2025-01-20',
    status: 'pending', // 'pending', 'under_review', 'approved', 'rejected'
    moveInDate: '2025-02-01',
    duration: '12 months',
    notes: 'Looking for a family home. We have 2 children.',
    documents: {
      employmentLetter: true,
      idCopy: true,
      references: true,
    },
  },
  {
    id: 'app2',
    houseId: 'rh2',
    houseTitle: 'Modern 2-Bedroom Apartment in Manzini',
    applicantName: 'Sarah Ndlovu',
    applicantEmail: 'sarah.ndlovu@email.com',
    applicantPhone: '+268 2505 8888',
    appliedDate: '2025-01-22',
    status: 'under_review',
    moveInDate: '2025-02-15',
    duration: '6 months',
    notes: 'Professional working in Manzini. Need temporary accommodation.',
    documents: {
      employmentLetter: true,
      idCopy: true,
      references: false,
    },
  },
  {
    id: 'app3',
    houseId: 'rh4',
    houseTitle: 'Luxury 4-Bedroom Flat in Mbabane',
    applicantName: 'David Mamba',
    applicantEmail: 'david.mamba@email.com',
    applicantPhone: '+268 2404 9999',
    appliedDate: '2025-01-15',
    status: 'approved',
    moveInDate: '2025-03-01',
    duration: '24 months',
    notes: 'Relocating family from South Africa.',
    documents: {
      employmentLetter: true,
      idCopy: true,
      references: true,
      creditCheck: true,
    },
  },
];

// Transportation For Hire Mock Data
export const mockTransportationVehicles = [
  {
    id: 'tv1',
    title: 'Comfortable 15-Seater Minibus - Cross Border',
    type: 'minibus', // 'minibus', 'bus', 'van', 'truck', 'sedan', 'suv'
    category: 'public_transport', // 'public_transport', 'cargo', 'passenger', 'luxury'
    images: [
      'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800',
      'https://images.unsplash.com/photo-1544620347-c4fd4a3d5958?w=800',
    ],
    capacity: 15,
    make: 'Toyota',
    model: 'Hiace',
    year: 2020,
    registration: 'SD 1234 AB',
    price: 2500, // per trip or per day
    priceType: 'per_trip', // 'per_trip', 'per_day', 'per_hour', 'per_km'
    currency: 'SZL',
    available: true,
    description: 'Comfortable 15-seater minibus perfect for cross-border trips. Regular service between Eswatini and South Africa. Air-conditioned, well-maintained vehicle with experienced driver.',
    features: [
      'Air Conditioning',
      'Music System',
      'Comfortable Seats',
      'Luggage Space',
      'Experienced Driver',
      'Insurance Included',
      'Border Crossing Experience',
    ],
    routes: [
      {
        origin: 'Mbabane',
        destination: 'Johannesburg',
        distance: '350 km',
        duration: '4-5 hours',
        price: 2500,
        borderCrossing: true,
      },
      {
        origin: 'Manzini',
        destination: 'Durban',
        distance: '450 km',
        duration: '5-6 hours',
        price: 3000,
        borderCrossing: true,
      },
    ],
    operatingDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    operatingHours: {
      start: '06:00',
      end: '20:00',
    },
    location: {
      area: 'Mbabane',
      city: 'Mbabane',
      address: 'Mbabane Bus Rank, Somhlolo Street',
      coordinates: {
        latitude: -26.3167,
        longitude: 31.1333,
      },
    },
    owner: {
      name: 'Swazi Transport Services',
      phone: '+268 2404 1111',
      email: 'info@swazitransport.sz',
      whatsapp: '+268 2404 1111',
      verified: true,
      rating: 4.8,
      responseTime: 'Within 2 hours',
      experience: '10+ years',
    },
    insurance: true,
    license: true,
    borderCrossing: true,
    postedDate: '2025-01-15',
    likes: 45,
    rating: 4.6,
    totalRatings: 28,
    status: 'available',
  },
  {
    id: 'tv2',
    title: 'Large Cargo Truck - 10 Ton Capacity',
    type: 'truck',
    category: 'cargo',
    images: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd65?w=800',
    ],
    capacity: null, // cargo capacity in tons
    cargoCapacity: 10, // tons
    make: 'Mercedes-Benz',
    model: 'Actros',
    year: 2019,
    registration: 'SD 5678 CD',
    price: 5000,
    priceType: 'per_day',
    currency: 'SZL',
    available: true,
    description: 'Heavy-duty cargo truck perfect for large shipments, construction materials, and bulk goods. Experienced driver available. Suitable for long-distance and cross-border transport.',
    features: [
      '10 Ton Capacity',
      'Hydraulic Tailgate',
      'Tarp Cover',
      'GPS Tracking',
      'Experienced Driver',
      'Insurance Included',
      'Loading Assistance',
    ],
    routes: [],
    operatingDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    operatingHours: {
      start: '07:00',
      end: '18:00',
    },
    location: {
      area: 'Manzini',
      city: 'Manzini',
      address: 'Industrial Area, Manzini',
      coordinates: {
        latitude: -26.4950,
        longitude: 31.3800,
      },
    },
    owner: {
      name: 'Heavy Haul Logistics',
      phone: '+268 2505 2222',
      email: 'haul@logistics.sz',
      whatsapp: '+268 2505 2222',
      verified: true,
      rating: 4.7,
      responseTime: 'Within 4 hours',
      experience: '15+ years',
    },
    insurance: true,
    license: true,
    borderCrossing: true,
    postedDate: '2025-01-18',
    likes: 32,
    rating: 4.7,
    totalRatings: 15,
    status: 'available',
  },
  {
    id: 'tv3',
    title: 'Luxury SUV - 7 Seater',
    type: 'suv',
    category: 'luxury',
    images: [
      'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800',
    ],
    capacity: 7,
    make: 'Toyota',
    model: 'Land Cruiser',
    year: 2022,
    registration: 'SD 9012 EF',
    price: 800,
    priceType: 'per_day',
    currency: 'SZL',
    available: true,
    description: 'Premium luxury SUV perfect for family trips, business travel, or special occasions. Fully equipped with modern amenities and comfortable seating.',
    features: [
      'Leather Seats',
      'Sunroof',
      'Premium Sound System',
      'Navigation System',
      'Reverse Camera',
      'Bluetooth',
      'Climate Control',
    ],
    routes: [],
    operatingDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    operatingHours: {
      start: '08:00',
      end: '22:00',
    },
    location: {
      area: 'Mbabane',
      city: 'Mbabane',
      address: 'The Gables, Mbabane',
      coordinates: {
        latitude: -26.3051,
        longitude: 31.1367,
      },
    },
    owner: {
      name: 'Premium Car Hire',
      phone: '+268 2404 3333',
      email: 'premium@carhire.sz',
      whatsapp: '+268 2404 3333',
      verified: true,
      rating: 4.9,
      responseTime: 'Within 1 hour',
      experience: '5+ years',
    },
    insurance: true,
    license: true,
    borderCrossing: true,
    postedDate: '2025-01-20',
    likes: 67,
    rating: 4.9,
    totalRatings: 34,
    status: 'available',
  },
  {
    id: 'tv4',
    title: 'Passenger Van - 12 Seater',
    type: 'van',
    category: 'passenger',
    images: [
      'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800',
    ],
    capacity: 12,
    make: 'Ford',
    model: 'Transit',
    year: 2021,
    registration: 'SD 3456 GH',
    price: 1800,
    priceType: 'per_day',
    currency: 'SZL',
    available: true,
    description: 'Spacious 12-seater passenger van ideal for group travel, airport transfers, and local tours. Comfortable and reliable.',
    features: [
      'Air Conditioning',
      'Comfortable Seats',
      'Luggage Space',
      'Music System',
      'Experienced Driver',
      'Insurance Included',
    ],
    routes: [],
    operatingDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    operatingHours: {
      start: '06:00',
      end: '21:00',
    },
    location: {
      area: 'Manzini',
      city: 'Manzini',
      address: 'Manzini Bus Rank',
      coordinates: {
        latitude: -26.4950,
        longitude: 31.3800,
      },
    },
    owner: {
      name: 'Group Travel Services',
      phone: '+268 2505 4444',
      email: 'group@travel.sz',
      whatsapp: '+268 2505 4444',
      verified: false,
      rating: 4.5,
      responseTime: 'Within 6 hours',
      experience: '8+ years',
    },
    insurance: true,
    license: true,
    borderCrossing: false,
    postedDate: '2025-01-22',
    likes: 28,
    rating: 4.5,
    totalRatings: 12,
    status: 'available',
  },
  {
    id: 'tv5',
    title: 'Medium Cargo Van - 3 Ton',
    type: 'van',
    category: 'cargo',
    images: [
      'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=800',
    ],
    capacity: null,
    cargoCapacity: 3, // tons
    make: 'Nissan',
    model: 'NV350',
    year: 2020,
    registration: 'SD 7890 IJ',
    price: 1200,
    priceType: 'per_day',
    currency: 'SZL',
    available: true,
    description: 'Medium cargo van perfect for small to medium deliveries, moving, and local transport. Easy to maneuver in city areas.',
    features: [
      '3 Ton Capacity',
      'Side Loading',
      'GPS Tracking',
      'Experienced Driver',
      'Insurance Included',
    ],
    routes: [],
    operatingDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    operatingHours: {
      start: '07:00',
      end: '19:00',
    },
    location: {
      area: 'Mbabane',
      city: 'Mbabane',
      address: 'Industrial Area, Mbabane',
      coordinates: {
        latitude: -26.3167,
        longitude: 31.1333,
      },
    },
    owner: {
      name: 'Quick Delivery Services',
      phone: '+268 2404 5555',
      email: 'delivery@quick.sz',
      whatsapp: '+268 2404 5555',
      verified: true,
      rating: 4.6,
      responseTime: 'Within 3 hours',
      experience: '6+ years',
    },
    insurance: true,
    license: true,
    borderCrossing: false,
    postedDate: '2025-01-19',
    likes: 19,
    rating: 4.6,
    totalRatings: 8,
    status: 'available',
  },
  {
    id: 'tv6',
    title: 'Large Passenger Bus - 50 Seater',
    type: 'bus',
    category: 'public_transport',
    images: [
      'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800',
    ],
    capacity: 50,
    make: 'Mercedes-Benz',
    model: 'Sprinter',
    year: 2018,
    registration: 'SD 2468 KL',
    price: 6000,
    priceType: 'per_trip',
    currency: 'SZL',
    available: true,
    description: 'Large passenger bus perfect for group tours, events, and long-distance travel. Comfortable seating with air conditioning and entertainment system.',
    features: [
      '50 Seats',
      'Air Conditioning',
      'Entertainment System',
      'Luggage Compartment',
      'Experienced Driver',
      'Insurance Included',
      'WiFi Available',
    ],
    routes: [
      {
        origin: 'Mbabane',
        destination: 'Cape Town',
        distance: '1400 km',
        duration: '16-18 hours',
        price: 6000,
        borderCrossing: true,
      },
    ],
    operatingDays: ['Monday', 'Wednesday', 'Friday', 'Sunday'],
    operatingHours: {
      start: '05:00',
      end: '22:00',
    },
    location: {
      area: 'Mbabane',
      city: 'Mbabane',
      address: 'Mbabane Bus Terminal',
      coordinates: {
        latitude: -26.3167,
        longitude: 31.1333,
      },
    },
    owner: {
      name: 'Long Distance Travel Co.',
      phone: '+268 2404 6666',
      email: 'longdistance@travel.sz',
      whatsapp: '+268 2404 6666',
      verified: true,
      rating: 4.8,
      responseTime: 'Within 2 hours',
      experience: '12+ years',
    },
    insurance: true,
    license: true,
    borderCrossing: true,
    postedDate: '2025-01-17',
    likes: 89,
    rating: 4.8,
    totalRatings: 45,
    status: 'available',
  },
  {
    id: 'tv7',
    title: 'Sedan Car - 4 Seater',
    type: 'sedan',
    category: 'passenger',
    images: [
      'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=800',
    ],
    capacity: 4,
    make: 'Toyota',
    model: 'Camry',
    year: 2021,
    registration: 'SD 1357 MN',
    price: 600,
    priceType: 'per_day',
    currency: 'SZL',
    available: true,
    description: 'Comfortable sedan car perfect for city travel, airport transfers, and short trips. Fuel efficient and reliable.',
    features: [
      'Air Conditioning',
      'Music System',
      'Bluetooth',
      'Navigation',
      'Experienced Driver',
      'Insurance Included',
    ],
    routes: [],
    operatingDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    operatingHours: {
      start: '07:00',
      end: '22:00',
    },
    location: {
      area: 'Manzini',
      city: 'Manzini',
      address: 'Manzini City Center',
      coordinates: {
        latitude: -26.4950,
        longitude: 31.3800,
      },
    },
    owner: {
      name: 'City Car Hire',
      phone: '+268 2505 7777',
      email: 'city@carhire.sz',
      whatsapp: '+268 2505 7777',
      verified: false,
      rating: 4.4,
      responseTime: 'Within 4 hours',
      experience: '3+ years',
    },
    insurance: true,
    license: true,
    borderCrossing: false,
    postedDate: '2025-01-21',
    likes: 24,
    rating: 4.4,
    totalRatings: 11,
    status: 'available',
  },
];